image: node:8

cache:
  paths:
  - docs/node_modules/

before_script:
  - cd docs/
  - npm install # Install project dependencies

pages:
  stage: deploy
  script:
  - npx @11ty/eleventy --output=../public/ --pathprefix=/prse/
  artifacts:
    paths:
    - public
  only:
  - master
